### ISSUE TITLE
Are we using `-s` flag?

### ISSUE THREAD

**Issue by mesaglio** [sisoputnfrba/so-deploy#7]
Is this flag working as we spected? We can remove?

**Comment by RaniAgus** [comment]
This was meant to be compatible with Eclipse project structure:
```
project
├── Debug
│   ├── main
│   └── makefile
└── src
    └── main.c
```
(or any other structure that doesn't have a Makefile placed in root for each module)

Eg:
```
./deploy.sh -s=Debug -p=project tp-2024-1c-example
```
